global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'java-service'
    static_configs:
      - targets: ['java-service:9000']
    
  - job_name: 'golang-service'
    static_configs:
      - targets: ['golang-service:9001']
    
  - job_name: 'php-service'
    static_configs:
      - targets: ['php-service:9002']
